server:
  port: 8080

spring:
  application:
    name: api-gateway

    # ============================================
    # SECURITY CONFIGURATION
    # ============================================
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/eco-ride-dev
            authorization-uri: http://localhost:8180/realms/eco-ride-dev/protocol/openid-connect/auth
            token-uri: http://localhost:8180/realms/eco-ride-dev/protocol/openid-connect/token
            user-info-uri: http://localhost:8180/realms/eco-ride-dev/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:8180/realms/eco-ride-dev/protocol/openid-connect/certs
            user-name-attribute: preferred_username

        registration:
          # SPA/Web Client - Authorization Code + PKCE
          keycloak:
            provider: keycloak
            client-id: eco-web-client
            # NO client-secret: cliente p√∫blico (PKCE)
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
              - trips:read
              - trips:write
              - payments:charge
              - notifications:send
            client-authentication-method: none

          # Internal Service-to-Service Client
          eco-internal:
            provider: keycloak
            client-id: eco-internal-client
            client-secret: GKL15VM9W3Hq1F5v9BV317fYuVh6p5bO
            authorization-grant-type: client_credentials
            scope:
              - trips:read
              - trips:write
              - payments:charge

      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/eco-ride-dev
          jwk-set-uri: http://localhost:8180/realms/eco-ride-dev/protocol/openid-connect/certs