global:
#  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'ECO-RIDE-LATAM'
    environment: 'dev'

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API Gateway
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'api-gateway'
          service: 'gateway'

  # Trip Service
  - job_name: 'trip-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:8085']
        labels:
          application: 'trip-service'
          service: 'business'

  # Payment Service
  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:8083']
        labels:
          application: 'payment-service'
          service: 'business'

  # Passenger Service
  - job_name: 'passenger-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:8082']
        labels:
          application: 'passenger-service'
          service: 'business'

  # Notification Service
  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          application: 'notification-service'
          service: 'business'