spring:
  application:
    name: trip-service

  # R2DBC Configuration
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/tripdb
    username: tripuser
    password: trippass
    pool:
      initial-size: 10
      max-size: 20


  # Flyway Configuration (Migrations run on JDBC)
  datasource:
    url: jdbc:postgresql://localhost:5433/tripdb
    username: tripuser
    password: trippass
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
    clean-disabled: true


server:
  port: 8085

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,flyway
  endpoint:
    health:
      show-details: always
    flyway:
      access: unrestricted

logging:
  level:
    com.rideshare: DEBUG
    org.springframework.cloud.stream: DEBUG
    org.flywaydb: INFO
